---
title: "Research Proposal Draft"
author: "Vanessa Mahan"
date: "2023-04-27"
output:
  pdf_document: default
  html_document: default
---
# Using a Coupled Model Approach to Predict Concentrations of Organic Mercury and Quantify the Impact on Fish Habitat for Penobscot River

## Abstract
## Introduction

## Research Tasks
To address the research gaps, three tasks will be completed as following: (1) evaluate transport characteristics of sediment throughout the Penobscot Estuary to link hydrodynamic conditions to the circulation of mercury-contaminated sediment and concentrations of methylmercury, (2) develop an updated suite of habitat indices linking hydrodynamic conditions to habitat quality for ten diadromous fish species native to the Penobscot River, and (3) estimate the geographic range and location of diadromous fish habitat throughout the Penobscot River and identify habitat areas with high levels of transport for mercury-contaminated sediment or high concentrations of methylmercury.

### Task I. Evaluate how tidal non-linearities affect the transport of sediment in the water column.
- 1 Manuscript

_Hypothesis I._

### Task II. Develop an updated suite of habitat models linking hydrodynamic conditions to habitat quality for ten diadromous fish species and estimate the geographic range and location of spawning and juvenile fish habitat throughout the Penobscot River.
- 2 Manuscripts
  - Model Document
  - Case Study
  
_Hypothesis II._

### Task III. Evaluate sediment transport characteristics and concentrations of methylmercury for diadromous fish habitat in the Penobscot River.
- 1 Manuscript

_Hypothesis III._

## Preliminary Results
## Dissertation Timeline
```{r echo=FALSE, fig.width=12, fig.height=6, out.width= "100%",fig.cap="Dissertation Timeline"}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(scales)

# Create sample data for timeline
timeline_data <- data.frame(
  Event = c("Task I. Tidal Non-Linearities", "Task II. Habitat Models","Task III. Contaminated Sediment", "Project Milestones"),
  Date = as.Date(c("2024-01-01", "2023-08-01", "2024-08-01","2023-07-01",#literature review
                   "2023-12-01",NA,"2024-12-31","2024-02-15",#Field work
                   NA,"2023-10-31","2025-05-01",NA, #Model Development
                   "2024-08-01","2024-02-01","2025-10-01","2024-07-01", #Data Analysis
                   "2025-01-01","2024-06-01","2026-02-01",NA, #Draft Manuscript
                   "2025-06-01","2024-10-01","2026-06-01","2026-05-15")),#Manuscript submission
  
  Description = c("Literature Review","Literature Review","Literature Review","Plan of Study",
                  "Field Work",NA,"Field Work","Research Proposal",
                  NA,"Model Development","Model Simulations",NA,
                  "Data Analysis","Data Analysis","Data Analysis","Canidacy Exam",
                  "Draft Manuscript","Draft Manuscript","Draft Manuscript",NA,
                  "Manuscript Submission","Manuscript Submission","Manuscript Submission","Defense")
)

# Create timeline plot
ggplot(timeline_data, aes(x = Date, y = Event, color = Event)) +
  geom_vline(xintercept = as.numeric(timeline_data$Date), linetype = "dashed", cex = 0.5) +
  geom_point() +
  scale_color_manual(labels = c("Project Milestones","Task I","Task II","Task III"), values = c("black", "red","blue","green")) +
  geom_text(aes(label = Description), hjust = -0.1, angle = 45, size = 3) +
  scale_x_date(date_breaks = "months", date_labels = "%m/%y") +
  labs(title = "Dissertation Timeline", x = "Month/year", y = "", color = "") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

## Planned Research Products

### Publications
- Habitat Suitability Models for ten diadromous fish in the Northeastern United States


### Conference Publications

### Misc. Publishable Products
- Grain Size Distribution dataset for the Penobscot River
- R-Package containing suitability models, processing functions, and mapping functions

## References