---
title: "Research Dissertation Outline Draft"
author: "Vanessa Mahan"
date: "2023-04-02"
output:
  pdf_document: default
  html_document: default
---
# Abstract

The Penobscot River Watershed is an important ecological and cultural region in Maine, USA, supporting a range of fish species, including many diadromous species. However, decades of industrial activity have resulted in high levels of mercury contamination in the river, which could be affecting fish populations. The goal of this research is to develop an integrated model of diadromous fish habitat suitability and mercury contamination in the Penobscot Watershed, with the aim of identifying areas of potential habitat for native species where high concentrations of methylmercury are present.

The first research task will focus on modeling the movement of contaminated sediment and the concentration of methylmercury for the Penobscot Watershed. This will be achieved using the sediment transport module of Delft3D to develop a hydrodynamic model. This model will estimate the geographic location and concentrations of methylmercury and describe the tidal influence as it relates to movement of the contaminate throughout the watershed. By understanding the movement and concentration of methylmercury, we can better understand how it may be affecting fish populations and identify areas of potential concern.

For the second research, suitability indices will be developed for fish habitat in the Penobscot Watershed. This task will involve a comprehensive literature review, as well as utilizing available data and existing suitability indices for similar species in other regions. Indices will be developed for nine diadromous fish species found in the Penobscot Watershed (alewives _Alosa psuedoharengus_, American eels _Anguilla rostrata_, American shad _A. sapidissima_, Atlantic salmon _Salmo salar_, Atlantic sturgeon _Acipenser oxyrinchus_, shortnose sturgeon _Acipenser brevirostrum_, blueback herring _A. aestivalis_, rainbow smelt _Osmerus mordax_, and striped bass _Morone saxatillis_), and will include separate indices for spawning and juvenile habitats. These indices will then be used in to identify areas of potential high fish habitat suitability within the Penobscot River.

For the third research task, a coupled model approach will be applied to the Penobscot River using the models developed in the first two research tasks. The fish habitat suitability indices and the mercury contamination model will be applied to the study area using existing observations of hydrodynamic and ecological data for the region. Using the outputs of the hydrodynamic model developed as inputs for the habitat suitability model, the geographic location and range of fish habitat with high concentrations of methylmercury can be identified. Integration of the models, can identify areas where contaminated habitats may be adversely affecting the restoration and recovery of fish populations.

In summary, this research aims to develop an integrated model of fish habitat suitability and mercury contamination for the Penobscot River. The overall objective is to understand the tidal influence on the movement of methylmercury throughout the watershed, understand the geographic location and range of fish habitat within the Penobscot River, and identify contaminated habitats that could be affecting the recovery of native fish populations.

# Introduction {-}

- Background
- Problem Statement
- Research Questions and Objectives

# Literature Review {-}

- Mercury contamination in the Penobscot Watershed
- Habitat suitability indices for diadromous fish species
- Modeling of sediment transport and methylmercury concentration in rivers

# Modeling the Movement of Contaminated Sediment and Methylmercury Concentration through the Penobscot River {-}

- Description of hydrodynamic model using Delft3D
- Estimation of geographic location and concentrations of methylmercury
- Assessment of tidal influence on methylmercury movement throughout the watershed

# Development of a Suite of Suitability Indicies for Nine Species of Diadromous Fish NAtive to the Penobscot River {-}

- Comprehensive literature review
- Use of available data and existing suitability indices for similar species in other regions
- Development of separate indices for nine diadromous fish species found in the Penobscot Watershed, including indices for spawning and juvenile habitats

# Using a Coupled Model Approach to Evaluate Methylmercury Contamination of Fish Habitat for the Penobscot River {-}

- Application of habitat suitability indices and the mercury contamination model to the study area
- Use of outputs from hydrodynamic model as inputs for the habitat suitability model
- Identification of areas where contaminated habitats may be adversely affecting the restoration and recovery of fish populations

# Significance and Expected Results {-}

- Contribution to the understanding of the impact of methylmercury on diadromous fish species in the Penobscot Watershed
- Identification of potential areas of concern for fish habitat and methylmercury contamination
- Use of modeling to inform conservation and restoration efforts

# References

# Appendices

## Appendix A: Geoprocessing Steps

- Detailed description of geoprocessing steps used in modeling

## Appendix B: Research Products

- List of research products generated from the study, including reports, datasets, and visualizations
